spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
#本地路径E:\阿里云api秘钥
#  jackson:
#    alicloud:
#      access-key:
#      secret-key:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
#动静分离后，将静态资源放在nginx中
#  mvc:
#    static-path-pattern: /static/**

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001
logging:
  level:
    com.feng.gulimall: debug

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
