spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tAFx7XuqqTQz1EpC4kp
      secret-key: gy2NYIv6brR4DMi1z6QqLfpHitV0jY
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: market-gulimall
  application:
    name: gulimall-third-party

server:
  port: 30000
